---
- name: GUI | Lookup current system general settings
  ansible.builtin.command: midclt call system.general.config
  register: sys_general_raw
  changed_when: false

- name: GUI | Set system general fact
  ansible.builtin.set_fact:
    sys_general: "{{ sys_general_raw.stdout | from_json }}"

- name: GUI | Disable HTTPS redirect and usage collection
  ansible.builtin.command: >
    midclt call system.general.update
    '{"ui_httpsredirect": false, "usage_collection": false}'
  changed_when: true
  when: >
    sys_general.ui_httpsredirect == true or
    sys_general.usage_collection == true
