---
- name: System Base | User setup
  ansible.builtin.import_tasks: user.yml

- name: System Base | Network configuration
  ansible.builtin.import_tasks: network.yml

- name: System Base | Mail configuration
  ansible.builtin.import_tasks: mail.yml

- name: System Base | GUI settings
  ansible.builtin.import_tasks: gui.yml

- name: System Base | Alert services
  ansible.builtin.import_tasks: alerts.yml

- name: System Base | LDAP authentication
  ansible.builtin.import_tasks: ldap.yml
  tags: [ldap]
