---
- name: User | Lookup Local Admin Details
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/user"
    method: GET
    body: {} 
  register: all_users

- name: User | Identify Admin User Object
  ansible.builtin.set_fact:
    target_user_obj: "{{ all_users.json | selectattr('username', 'equalto', truenas_user) | first | default(None) }}"

- name: User | Update Admin Alert Email
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/user/id/{{ target_user_obj.id }}"
    method: PUT
    body:
      email: "{{ alert_email }}"
  when: 
    - target_user_obj is not none
    - target_user_obj.email != alert_email

- name: Network | Lookup Configuration
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/network/configuration/"
    method: GET
  register: truenas_net_config

- name: Network | Set Hostname and Domain
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/network/configuration/"
    method: PUT
    body:
      hostname: "{{ truenas_hostname }}"
      domain: "{{ truenas_domain }}"
  when: >
    truenas_net_config.json.hostname != truenas_hostname or
    truenas_net_config.json.domain != truenas_domain

- name: Mail | Lookup Current SMTP Configuration
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/mail"
    method: GET
  register: current_mail_config

- name: Mail | Configure AWS SES SMTP
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/mail"
    method: PUT
    body: >-
      {{
        {
          "outgoingserver": smtp_server,
          "port": smtp_port | int,
          "security": smtp_security,
          "fromemail": from_email,
          "fromname": "TrueNAS - " ~ truenas_hostname,
          "smtp": true,
          "user": smtp_user,
          "pass": smtp_pass
        }
      }}
  no_log: true
  when: >
    current_mail_config.json.outgoingserver != smtp_server or
    current_mail_config.json.port != smtp_port | int or
    current_mail_config.json.security != smtp_security or
    current_mail_config.json.fromemail != from_email or
    current_mail_config.json.user != smtp_user

- name: ACME | Lookup DNS Authenticators
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/acme/dns/authenticator"
    method: GET
    body: {}
  register: truenas_authenticators

- name: ACME | Create Cloudflare Authenticator
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/acme/dns/authenticator"
    method: POST
    body:
      name: "{{ acme_dnstype }}_auth"
      attributes:
        authenticator: "{{ acme_dnstype }}"
        api_token: "{{ cloudflare_api_token }}"
  when: truenas_authenticators.json | selectattr('name', 'equalto', acme_dnstype ~ "_auth") | list | length == 0
  register: auth_create_res
  no_log: true

- name: PKI | Lookup Existing Certificates
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/certificate"
    method: GET
    body: {}
  register: truenas_certs

- name: PKI | Create CSR
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/certificate"
    method: POST
    body:
      name: "{{ csr_name }}"
      create_type: "CERTIFICATE_CREATE_CSR"
      key_type: "{{ ssl_key_type }}"
      ec_curve: "{{ ec_curve }}"
      digest_algorithm: "{{ digest_algorithm }}"
      common: "{{ ssl_common }}"
      san:
        - "{{ ssl_san }}"
  register: csr_trigger
  when: truenas_certs.json | selectattr('name', 'equalto', csr_name) | list | length == 0

- name: PKI | Wait for CSR Job
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/core/get_jobs/?id={{ csr_trigger.json }}"
    method: GET
  register: csr_job_status
  until: csr_job_status.json[0].state not in ['WAITING', 'RUNNING']
  retries: 10
  delay: 2
  when: csr_trigger is not skipped
  failed_when: csr_job_status.json[0].state == 'FAILED'

- name: PKI | Define CSR and Authenticator IDs
  ansible.builtin.set_fact:
    target_csr_id: >-
      {% if csr_trigger is not skipped %}
        {{ csr_job_status.json[0].result.id | int }}
      {% else %}
        {{ (truenas_certs.json | default([]) | selectattr('name', 'equalto', csr_name) | map(attribute='id') | list | first) | default(0) | int }}
      {% endif %}
    target_auth_id: >-
      {% if auth_create_res is not skipped %}
        {{ auth_create_res.json.id | int }}
      {% else %}
        {{ (truenas_authenticators.json | default([]) | selectattr('name', 'equalto', acme_dnstype ~ '_auth') | map(attribute='id') | list | first) | default(0) | int }}
      {% endif %}
  when: truenas_certs.json | selectattr('name', 'equalto', ssl_cert_name) | list | length == 0

- name: PKI | Create ACME Signed Certificate
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/certificate"
    method: POST
    body: >-
      {{
        {
          "name": ssl_cert_name,
          "create_type": "CERTIFICATE_CREATE_ACME",
          "acme_directory_uri": "https://acme-v02.api.letsencrypt.org/directory",
          "csr_id": target_csr_id | int,
          "tos": true,
          "dns_mapping": {
            ssl_common: target_auth_id | int
          }
        }
      }}
  register: ssl_trigger
  when: truenas_certs.json | selectattr('name', 'equalto', ssl_cert_name) | list | length == 0

- name: PKI | Wait for ACME SSL Job
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/core/get_jobs/?id={{ ssl_trigger.json }}"
    method: GET
  register: ssl_job_status
  until: ssl_job_status.json[0].state not in ['WAITING', 'RUNNING']
  retries: 40
  delay: 15
  when: ssl_trigger is not skipped
  failed_when: ssl_job_status.json[0].state == 'FAILED'

- name: GUI | Define Final Certificate ID
  ansible.builtin.set_fact:
    final_cert_id: >-
      {% if ssl_trigger is not skipped %}
        {{ ssl_job_status.json[0].result.id | int }}
      {% else %}
        {{ (truenas_certs.json | default([]) | selectattr('name', 'equalto', ssl_cert_name) | map(attribute='id') | list | first) | default(0) | int }}
      {% endif %}

- name: GUI | Lookup Current System General Settings
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/system/general"
    method: GET
  register: truenas_system_general

- name: GUI | Identify Currently Active Certificate Name
  ansible.builtin.set_fact:
    current_cert_name: "{{ (truenas_certs.json | selectattr('id', 'equalto', truenas_system_general.json.ui_certificate) | map(attribute='name') | first) | default('Unknown') }}"

- name: GUI | Apply SSL Certificate to Web Interface
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/system/general"
    method: PUT
    body_format: json
    body: >-
      {{
        {
          "ui_certificate": final_cert_id | int
        }
      }}
  register: system_update
  when: current_cert_name != ssl_cert_name

- name: GUI | Restart HTTP Service
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/system/general/ui_restart"
    method: POST
  when: >
    (ssl_trigger is changed) or 
    (system_update is changed)
  async: 30
  poll: 0

- name: GUI | Disable HTTPS Redirect and Usage Collection
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/system/general"
    method: PUT
    body:
      ui_httpsredirect: false
      usage_collection: false
  when: >
    truenas_system_general.json.ui_httpsredirect == true or
    truenas_system_general.json.usage_collection == true