---
- name: Storage | ACLs
  ansible.builtin.import_tasks: acl.yml
  tags: [acl]

- name: Storage | Shares
  ansible.builtin.import_tasks: shares.yml

- name: Storage | Services
  ansible.builtin.import_tasks: services.yml

- name: Storage | Snapshots
  ansible.builtin.import_tasks: snapshots.yml

- name: Storage | Cloud sync
  ansible.builtin.import_tasks: cloudsync.yml

- name: Storage | Scrub
  ansible.builtin.import_tasks: scrub.yml
