---
- name: Hardening | User lockdown
  ansible.builtin.import_tasks: users.yml

- name: Hardening | SSH hardening
  ansible.builtin.import_tasks: ssh.yml

- name: Hardening | SMB service restrictions
  ansible.builtin.import_tasks: smb.yml
