---
- name: User | Lookup truenas_admin builtin account
  ansible.builtin.command: >
    midclt call user.query '[["username", "=", "truenas_admin"]]'
  register: system_hardening_truenas_admin_raw
  changed_when: false

- name: User | Set truenas_admin fact
  ansible.builtin.set_fact:
    system_hardening_truenas_admin_list: "{{ system_hardening_truenas_admin_raw.stdout | from_json }}"

- name: User | Lock truenas_admin account
  ansible.builtin.command: >
    midclt call user.update
    '{{ system_hardening_truenas_admin_list[0].id }}'
    '{"locked": true}'
  changed_when: true
  when:
    - system_hardening_truenas_admin_list | length > 0
    - not system_hardening_truenas_admin_list[0].locked
