---
- name: Group | Fetch Existing Groups
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/group"
    method: GET
    body: {}
  register: existing_groups

- name: Group | Create Service Groups
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/group"
    method: POST
    body: "{{ {'name': item.name, 'gid': item.gid | int} }}"
  loop: "{{ service_groups }}"
  when: >
    item.name not in (existing_groups.json | map(attribute='group') | list)
  register: group_creation

- name: Group | Refresh Existing Groups
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/group"
    method: GET
    body: {}
  register: refreshed_groups
  when: group_creation is changed

- name: User | Map Group Names to IDs
  set_fact:
    group_lookup: >-
      {{ 
        (refreshed_groups.json if group_creation is changed else existing_groups.json) 
        | items2dict(key_name='group', value_name='id') 
      }}

- name: User | Fetch Existing Users
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/user"
    method: GET
    body: {}
  register: existing_users

- name: User | Create Service Users
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}/api/v2.0/user"
    method: POST
    body: >
      {{
        {
          "username": item.name,
          "uid": item.uid | int,
          "group": group_lookup[item.group] | int,
          "full_name": item.comment,
          "password_disabled": true,
          "smb": false,
          "locked": false,
          "shell": "/usr/sbin/nologin"
        }
      }}
  loop: "{{ service_users }}"
  when: >
    item.name not in (existing_users.json | map(attribute='username') | list)